### ISSUE TITLE
166 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by anhnt92** [sdkbox/sdkbox-facebook-sample#2] opened 2015-10-22 04:45 UTC
Hi, when build my game project with sdkbox facebook plugin, i get an error  166 duplicate symbols for architecture x86_64 such as duplicate symbol _llvm.cmdline in:
    /path/cpp/proj.ios_mac/FBSDKCoreKit.framework/FBSDKCoreKit(FBSDKAppEvents.o)

**Comment by darkdukey** [comment] 2015-11-04 00:48
What other plugins are you using in your project?

**Comment by darkdukey** [comment] 2015-12-22 00:15
Closing due to not able to reproduce

**Closed by darkdukey** 2015-12-22 00:15 UTC
